config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('register.urls')),
    path('', include('my_page.urls')),
    path('', include('diagnotis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = 'home'




urlpatterns = [
    ##COMPLETE
    path('', views.Top.as_view(), name='top'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('question/', views.Question.as_view(), name='question'),
    path('instructions/', views.Instructions.as_view(), name='instructions'),
    path('order_job/', views.Order_Job.as_view(), name='order_job'),

    path('research_result/', views.ResearchResult.as_view(), name='research_result'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_detail'),
    path('like/<int:order_id>', views.like, name='like'),

    path('role_choice/', views.RoleChoice.as_view(), name='role_choice'),
    path('add_role/',views.addRole, name='add_role'),
    path('add_profile/',views.addProfile,name="add_profile"),
    path('change_profile',views.change_profile,name="change_profile")

]

my_page/urls.py
from django.urls import path
from . import views


app_name = 'my_page'


urlpatterns = [
    path('my_menu/', views.menu, name='my_menu'),

    path('order_submit/<int:order_id>', views.submit, name='submit'),


    path('profile/', views.Profile.as_view(), name='profile'),

    path('register_info/', views.Register_Info.as_view(), name='register_info'),
    path('orderer_info/', views.Orderer_Info.as_view(), name='orderer_info'),
    path('contractor_info/', views.Contractor_Info.as_view(), name='contractor_info'),

    path('message/', views.message, name='message'),
    path('message/<int:customer_id>/', views.message, name='message_detail'),

    path('order_decide/<int:order_id>/<int:customer_id>/', views.order_decide, name='order_decide'),

    path('pay/<int:order_id>', views.pay, name='pay'),
    path('pay_credit/<int:order_id>',views.pay_credit,name='pay_credit'),

    path('cancel/<int:order_id>',views.cancel,name='cancel'),
    path('order_fin/<int:order_id>',views.order_fin,name='order_fin'),
    path('complete/<int:order_id>', views.complete, name="complete"),


    path('favorite_list/', views.Favorite_List.as_view(), name='favorite_list'),
    path('request_job/', views.Request_Job.as_view(), name='request_job'),
    path('consent_list/', views.Consent_list.as_view(), name='consent_list'),
    path('trade_list/', views.Trade_list.as_view(), name='trade_list'),
    path('complate_list/', views.Complate_list.as_view(), name='complate_list'),



    path('comfirm/', views.Comfirm.as_view(), name='comfirm'),
    path('change/', views.Change.as_view(), name='change'),
    path('approval/', views.Approval.as_view(), name='approval'),
    path('cancel/', views.Cancel.as_view(), name='cancel'),
    path('complate/', views.Complate.as_view(), name='complate'),

]

home/models.py
from django.db import models
from register.models import User
# Create your models here.

class MstLang(models.Model):
    class Meta:
        verbose_name_plural="M_言語"
    name = models.CharField(max_length=10)
    def __str__(self):
        return self.name

class MstCost(models.Model):
    class Meta:
        verbose_name_plural="M_コスト"
    name = models.CharField(max_length=10)
    def __str__(self):
        return self.name

class MstSkill(models.Model):
    class Meta:
        verbose_name_plural="M_スキル"
    name = models.CharField(max_length=10)
    def __str__(self):
        return self.name

class CreditInfomation(models.Model):
    class Meta:
        verbose_name_plural="クレジット情報"
    name=models.CharField(max_length=10)
    credit_infomation = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

class BuyerProfile(models.Model):
    class Meta:
        verbose_name_plural="購入者プロフィール"
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    picture = models.ImageField(blank=True,null=True)
    estimate_point=models.FloatField(default=0)
    credit_customer=models.CharField(max_length=50,blank=True)
    credit_info=models.ManyToManyField(CreditInfomation,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)





class MakerProfile(models.Model):
    class Meta:
        verbose_name_plural="作成者プロフィール"
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    picture = models.ImageField(blank=True,null=True)
    lang = models.ManyToManyField(MstLang,blank=True)
    cost = models.ForeignKey(MstCost,on_delete=models.CASCADE,blank=True,null=True)
    skill = models.ManyToManyField(MstSkill,blank=True)

    estimate_point=models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




class MstOrderType(models.Model):
    class Meta:
        verbose_name_plural="オーダー属性"
    name = models.CharField("名前",max_length=50)
    def __str__(self):
        return self.name
class MstStatus(models.Model):
    name=models.CharField(max_length=4)
    def __str__(self):
        return self.name

class Order(models.Model):
    class Meta:
        verbose_name_plural="オーダー"

    buyer = models.ForeignKey(User,on_delete=models.CASCADE,related_name="Buyer")

    title = models.CharField(max_length=20)

    body = models.TextField()

    order_type = models.ForeignKey(MstOrderType,on_delete=models.CASCADE)

    picture = models.ImageField(blank=True,null=True)


    order_finish_time = models.DateTimeField(blank=True,null=True)

    cost = models.IntegerField()

    status = models.ForeignKey(MstStatus,on_delete=models.CASCADE,null=True,blank=True)

    order_post=models.BooleanField(default=False)
    order_post_at = models.DateTimeField(blank=True,null=True)

    makers = models.ManyToManyField(User,blank=True)
    maker_decided = models.ForeignKey(User, on_delete=models.CASCADE, related_name="Maker_decided",blank=True,null=True)
    order_confirm = models.BooleanField(default=False)
    order_confirm_at = models.DateTimeField(blank=True,null=True)
    order_pay = models.BooleanField(default=False)
    order_pay_at = models.DateTimeField(blank=True,null=True)
    order_finish = models.BooleanField(default=False)
    order_finish_at = models.DateTimeField(blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.buyer.email

class OrderMessage(models.Model):
    class Meta:
        verbose_name_plural="オーダーメッセージ"

    buyer = models.ForeignKey(User,on_delete=models.CASCADE,related_name="MessageBuyer")
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="MessageMaker")
    talker = models.ForeignKey(User,on_delete=models.CASCADE,related_name="Talker")
    body= models.TextField()
    file = models.FileField(blank=True)


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body

class Like(models.Model):
    class Meta:
        verbose_name_plural="favorite"
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="user")
    like_order = models.ForeignKey(Order, on_delete=models.CASCADE)
    del_flg=models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Contact(models.Model):
    class Meta:
        verbose_name_plural="コンタクト"
    user = models.CharField("User Name",max_length=100)
    email=models.EmailField("E-MAIL")
    message=models.TextField("Message")
    file = models.FileField("ファイル",null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user

home/forms.py
from django import forms
from .models import MakerProfile,BuyerProfile,MstLang,MstSkill,Contact,Order,OrderMessage
from register.models import User





class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('last_name', 'first_name')

class MakerProfileForm(forms.ModelForm):

    class Meta:
        model = MakerProfile
        fields = ('picture','lang','cost','skill')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['lang'].widget = forms.CheckboxSelectMultiple()
        self.fields['lang'].queryset = MstLang.objects
        self.fields['skill'].widget = forms.CheckboxSelectMultiple()
        self.fields['skill'].queryset = MstSkill.objects



class BuyerProfileForm(forms.ModelForm):

    class Meta:
        model = BuyerProfile
        fields = ('picture',)


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('user','email','message','file',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs.update({
            'class': 'form-control required',
            'placeholder':'Your Name',
            'data-placement':'top',
            'data-trigger':'manual',
            'data-content':'Must be at least 3 characters long, and must only contain letters.'})
        self.fields['email'].widget.attrs.update({
            'class':'form-control email',
            'placeholder':'email@xxx.com',
            'data-placement':'top',
            'data-trigger':'manual',
            'data-content':'Must be a valid e-mail address (user@gmail.com)',
        })
        self.fields['message'].widget.attrs.update({
            'class':'form-control',
            'placeholder':"Your message here..",
            'data-placement':'top',
            'data-trigger':'manual',
        })


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('title','body','order_type','order_finish_time','cost',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class':'form-control',
            'placeholder':"タイトルを入れてください",
            'data-placement':'top',
            'data-trigger':'manual',
            "data-content" :"依頼の内容入力",
        })
        self.fields['order_type'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['body'].widget.attrs.update({
            'class':'form-control',
        })
        self.fields['cost'].widget.attrs.update({
            'class':'form-control',
        })
        self.fields['order_finish_time'].widget.attrs.update({
            'class':'form-control',
        })



class SearchForm(forms.Form):

    title = forms.CharField(
        initial='',
        label='タイトル',
        required = False, # 必須ではない
    )

home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserForm,MakerProfileForm,BuyerProfileForm,ContactForm,OrderForm,SearchForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


##model
from .models import MakerProfile,Like,BuyerProfile,Contact,Order,MstStatus,Like
from .models import Order as OrderModel
from register.models import UserRole
from django.db.models import Q

import datetime


##COMPLETE##
class Top(generic.TemplateView):
    template_name = 'home/Top.html'

class About(generic.TemplateView):
    template_name = 'home/about.html'


class Contact(generic.CreateView):
    model = Contact
    form_class = ContactForm
    template_name = "home/contact.html"
    success_url = "/"  # 成功時にリダイレクトするURL

class Diagnosis(generic.TemplateView,LoginRequiredMixin):
    template_name = 'home/diagnosis.html'


class Instructions(generic.TemplateView):
    template_name = 'home/instractions.html'

class Question(generic.TemplateView):
    template_name = 'home/question.html'


class Order_Job(generic.CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'home/order_job.html'
    success_url = "/"  # 成功時にリダイレクトするURL
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        status=MstStatus.objects.get(id=1)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.buyer= request.user
            obj.order_post=True
            obj.order_post_at=datetime.datetime.now()
            obj.status=status
            obj.save()
        return redirect('/')


class ResearchResult(generic.ListView,LoginRequiredMixin):
    model = Order
    template_name = "home/research_result.html"
    paginate_by = 10

    #検索する文字の情報を受け取っている。
    def post(self, request, *args, **kwargs):
        form_value = [
            self.request.POST.get('title', None),
        ]
        request.session['form_value'] = form_value
        # 検索時にページネーションに関連したエラーを防ぐ
        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()
        return self.get(request, *args, **kwargs)

    # formの{{}}を表示させるためのデータを作成する。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = ''
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
        default_data = {'title': title,  # タイトル
                        }
        test_form = SearchForm(initial=default_data)  # 検索フォーム
        context['test_form'] = test_form
        return context

    # データの抽出・制限。
    def get_queryset(self):
        # sessionに値がある場合、その値でクエリ発行する。
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
            # 検索条件
            condition_title = Q()
            print(title)
            if len(title) != 0 and title[0]:
                condition_title = Q(title__icontains=title)

            status = get_object_or_404(MstStatus,id=1)
            return Order.objects.select_related().filter(condition_title,status=status)
        else:
            status = get_object_or_404(MstStatus, id=1)
            return Order.objects.filter(status=status)












def order_detail(request,order_id):
    order=OrderModel.objects.get(id=order_id)
    data={
        "order":order,
    }
    return render(request,'home/order_detail.html',data)

def like(request,order_id):

    like_order = OrderModel.objects.get(id=order_id)
    like,_ = Like.objects.get_or_create(user=request.user,like_order=like_order)
    like.save()

    return redirect('/')



##COMPLETE##
class RoleChoice(generic.TemplateView,LoginRequiredMixin):
    template_name = 'home/menu/role_choice.html'

def addRole(request):
    user=request.user
    user_role=UserRole.objects.get(id=int(request.POST["role"]))
    user.user_role=user_role
    user.save()
    user_forms=UserForm()
    if user_role.id==1:
        profile_forms=MakerProfileForm()
    else:
        profile_forms=BuyerProfileForm()
    data={
        "user_forms":user_forms,
        "profile_forms":profile_forms
    }
    return render(request,'home/menu/profile_edit.html',data)


def addProfile(request):
    user=request.user
    user.first_name=request.POST["first_name"]
    user.last_name=request.POST["last_name"]
    user.save()
    if user.user_role.id==1:
        profile_forms = MakerProfileForm(request.POST,request.FILES)
    else:
        profile_forms = BuyerProfileForm(request.POST,request.FILES)
    if profile_forms.is_valid():
        profile=profile_forms.save(commit=False)
        profile.user=request.user
        profile.save()
        return redirect("/my_menu/")



def change_profile(request):
    user=request.user
    user_forms=UserForm(instance=user)
    if user.user_role.id==1:
        profile=MakerProfile.objects.get(user=user)
        profile_forms=MakerProfileForm(instance=profile)

    else:
        profile = BuyerProfile.objects.get(instance=profile)
        profile_forms=BuyerProfileForm()


    data={
        "user_forms":user_forms,
        "profile_forms":profile_forms
    }
    return render(request,'home/menu/profile_edit.html',data)

templates/home/contact.html
{% extends "base.html" %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>お問い合わせ</title>
    <!-- CSS START -->
     <style type="text/css">
      .center {
      text-align:center;
      }
     </style>
    <!-- CSS END -->
</head>


{% block content %}

<body>

      <div class="modal-dialog">
        <div class="modal-content">

              <div class="modal-header">
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >　　　 　お問い合わせ</h3>
                  </div>
              </div>


              <div class="modal-body">
                  <div class="form-group"><label>User name</label>
                      {{form.user}}
                  </div>
                  <div class="form-group"><label>E-Mail</label>
                      {{form.email}}
                  </div>
                  <div class="form-group"><label>Message</label>
                      {{form.message}}
                      {{form.file}}
                  </div>
              </div>

              <div class="modal-footer">
              <div class="container-fluid">
                <div class="row">

                        <div class="center col-4">
            　          </div>
                        <div class="center col-3">
                            <a href=""><button input="submit" class="btn btn-warning">　 送る 　</button>
            　          </div>
                </div>
              </div>
              </div>
          </div>
        </div>
      </div>
    </div>
   </div>
  </div><br><br>
</body>
</html>
{% endblock %}

templates/home/diagnosis.html
{% extends "base.html" %}
{% load static %}
{% block css %}

{% endblock %}
{% block js %}

{% endblock %}

{% block content %}
    
    <!-- 作業フローの解説 -->
        <section class="marketing-site-three-up">
            <h2 class="marketing-site-three-up-headline">Furry, Reliable, Cuddly</h2>
            <div class="row medium-unstack">
            <div class="columns">
                <i class="fa fa-gg" aria-hidden="true"></i>
                <h4 class="marketing-site-three-up-title">Keyless Entry</h4>
                <p class="marketing-site-three-up-desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi sint, voluptatibus eaque natus ad eius.</p>
            </div>
            <div class="columns">
                <i class="fa fa-user-o" aria-hidden="true"></i>
                <h4 class="marketing-site-three-up-title">Invincible Igloo</h4>
                <p class="marketing-site-three-up-desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi sint, voluptatibus eaque natus ad eius.</p>
            </div>
            <div class="columns">
                <i class="fa fa-check-square-o" aria-hidden="true"></i>
                <h4 class="marketing-site-three-up-title">Stereo System</h4>
                <p class="marketing-site-three-up-desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi sint, voluptatibus eaque natus ad eius.</p>
            </div>
            </div>
      　</section>     


{% endblock %}

templates/home/order_detail.html
{% extends "base.html" %}
{% load static %}
{% block css %}
     <style type="text/css">
      .center {
      text-align: center;
      }
     </style>
<link rel="stylesheet" href="{% static 'home/css/about.css' %}">
{% endblock %}
{% block js %}

{% endblock %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
{% block content %}
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">

            <div style="margin:auto"><h3 id="myModalLabel">仕事の発注</h3></div>
              <a  href="/"><button type="button" class="close">×</button></a>
          </div>
          <div class="modal-body">
              <div class="form-group">
              <label>タイトル</label>
                {{order.title}}
              </div>
              <p><label for="message" >依頼したい項目</label></p><br>
              <div class="form-group">
                {{order.order_type}}
              </div><br>

              <div class="form-group">
              <label>要望詳細</label>
                {{order.body}}
              </div>

            　<div class="form-group">
                  <label>納品希望日</label>
                    {{order.order_finish_time}}
              </div>

              <div class="form-group">
                  <label>依頼金額の目安</label>
                    {{order.cost}}円
          　　</div>


              <div class="modal-footer">
                <div class="text-center">
                <a href="/my_menu/"  class="btn btn-default">　 戻る 　</a>
　           </div></hr><br>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/home/question.html
{% extends "base.html" %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>よくある質問</title>
    <!-- CSS START -->
     <style type="text/css">
      .center {
      text-align: center;
      }
      .question {
      color:#FF9B00;
      }
      .answer {
      color:#3676E0;
      }
     </style>
    <!-- CSS END -->
</head>

{% block content %}
<body>

      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <div class="center"><h2 id="myModalLabel">　　　　よくある質問</h2></div>
          </div>
          <div class="modal-body">
              <div class="form-group"><label></label>
                <h5 class="">
                <span class="question">Q:</span>
                サイトの利用は無料ですか?
                </h5>

                <h6 class="">
                <span class="answer">A:</span>
                 登録から発注・受注まで無料でご利用いただけます。
                </h6>
              </div><br>

              <div class="form-group"><label></label>
                <h5 class="">
                <span class="question">Q:</span>
                仕事依頼をしたのに返事が来ません。
                </h5>

                <h6 class="">
                <span class="answer">A:</span>
                 ログインをして、マイメニューのメッセージから仕事依頼をし
                 <br>　 た方に連絡を取ってみてください。
                </h6>
              </div><br>


              <div class="form-group"><label></label>
                <h5 class="">
                <span class="question">Q:</span>
                仕事依頼の際の契約金額の決め方について
                </h5>

                <h6 class="">
                <span class="answer">A:</span>
                仕事依頼内容をご確認いただいた上で、 受注者・発注者の双
                <br>　 方の希望に沿った金額を考慮して下さい。
                <br>　 金額に関する交渉等はマイメニューのお気に入りからメッセー
                <br>　 ジを送付してお話し合い下さい。
                </h6>
              </div><br>

              <div class="form-group"><label></label>
                <h5 class="">
                <span class="question">Q:</span>
                仕事は途中で辞退できますか?
                </h5>

                <h6 class="">
                <span class="answer">A:</span>
                 双方の話し合いで同意が取れましたらマイメニューの取引一覧
                 <br>　 から対象の案件の欄にある「キャンセル」ボタンより辞退が
                 <br>　 可能です。
                </h6>
              </div><br>

              <div class="form-group"><label></label>
                <h5 class="">
                <span class="question">Q:</span>
                その他、分からないことがあります。
                </h5>

                <h6 class="">
                <span class="answer">A:</span>
                 その他質問したいことがある場合は「お問い合わせ」から内
                 <br>　 容及びファイルなどを記入・添付のほど送信して下さい。
                 <br>　 通常、一週間以内に運営より記入していただいたメールアド
                 <br>　 レスに回答をさせていただきます。
                </h6>
              </div><br>

             <div class="modal-footer">
              <div class="container-fluid">
              <div class="row">
                  <div class="center col-4"></div>
                <div class="center col-3">
                 <a href="{% url 'home:top' %}">
                     <button input="submit" class="btn btn-warning">　 戻る 　</button></a>
                </div>
            　  </div>
              </div>
             </div>

             </div>
        </div>
      </div>
    </div><br><br>



</body>
</html>
{% endblock %}

templates/home/research_result.html
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>仕事一覧</title>
        <style type="text/css">
        </style>
    </head>
    <body>

        <div class="container">
            <div class="row">
                <h1>仕事一覧</h1><br>
                <nav class="navbar navbar-default query" role="query">
                    <div class="container-fluid">
                        <div class="navbar-header">


                        </div>
                        <div class="collapse navbar-collapse" id="">
                            <div class="navbar-form navbar-left">
                                <form method="POST">
                                    {% csrf_token %}
                                    <input type="text"  name="title" class="form-control" />
                                    <button type="submit" class="btn btn-default">検索</button>
                                </form>

                            </div>
                        </div>

                    </div>
                </nav>
                <div class="table-responsive col-md-12">
                    <table class="table table-striped table-hover">

                        <thead>
                            <tr>
                                <th class="center">依頼日</th>
                                <th class="center">タイトル</th>
                                <th class="center">状態</th>
                                <th class="center">詳細</th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for order in object_list %}
                            <tr>
                                <td class="col-md-2"><p>{{order.order_post_at}}</p></td>
                                <td class="col-md-4"><p>{{order.title}}</td>
                                <td class="col-md-2"><p>
                                    <span class="label label-success">{{order.status}}</span>
                                </p></td>
                                <td class="col-md-3"><p>
                                    <a href="{% url 'home:order_detail' order.id %}"class="btn btn-default ”form-inline”">仕事の詳細</a>
                                    <a href="{% url 'home:like' order.id %}" class="btn btn-warning ”form-inline”">お気に入り</a>
                                    <a href="{% url 'my_page:submit' order.id %}" class="btn btn-primary" ”form-inline”">申し込み</a>
                                </p></td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <nav aria-label="Page navigation example">

    <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

</nav>
            </div>
        </div>
    </body>
</html>