config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('register.urls')),
    path('', include('my_page.urls')),
    path('', include('diagnotis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = 'home'




urlpatterns = [
    ##COMPLETE
    path('', views.Top.as_view(), name='top'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('question/', views.Question.as_view(), name='question'),
    path('instructions/', views.Instructions.as_view(), name='instructions'),
    path('order_job/', views.Order_Job.as_view(), name='order_job'),

    path('research_result/', views.ResearchResult.as_view(), name='research_result'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_detail'),
    path('like/<int:order_id>', views.like, name='like'),

    path('role_choice/', views.RoleChoice.as_view(), name='role_choice'),
    path('add_role/',views.addRole, name='add_role'),
    path('add_profile/',views.addProfile,name="add_profile"),
    path('change_profile',views.change_profile,name="change_profile")

]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),

    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

register/models.py
# Djangoのモデルの呼び出し
from django.db import models

# メールを送る
from django.core.mail import send_mail

# ユーザーのフォームモデル
from django.contrib.auth.models import PermissionsMixin, UserManager

# ユーザのクラスモデルの継承
from django.contrib.auth.base_user import AbstractBaseUser

# 文字列を多言語化
from django.utils.translation import ugettext_lazy as _

# 時刻の表示・変換
from django.utils import timezone

class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

######　ここまで

class UserRole(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    user_role = models.ForeignKey(UserRole,on_delete=models.CASCADE,blank=True,null=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % ( self.last_name,self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email

register/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm,PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        fields = ('last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class EmailChangeForm(forms.ModelForm):
    """メールアドレス変更フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model,login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView,PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import redirect,resolve_url
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm,MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm,EmailChangeForm
)

User = get_user_model()


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LogoutView):
    """ログアウトページ"""
    template_name = 'register/top.html'



class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('register/mail_template/create/subject.txt', context)
        message = render_to_string('register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return login(request, user, backend='django.contrib.auth.backends.ModelBackend')


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'register/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])

class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'register/password_change_done.html'

class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'register/password_reset_complete.html'

class EmailChange(LoginRequiredMixin, generic.FormView):
    """メールアドレスの変更"""
    template_name = 'register/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string('register/mail_template/email_change/subject.txt', context)
        message = render_to_string('register/mail_template/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('register:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    """メールアドレスの変更メールを送ったよ"""
    template_name = 'register/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    """リンクを踏んだ後に呼ばれるメアド変更ビュー"""
    template_name = 'register/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

templates/register/email_change_complete.html
{% extends "base.html" %}
{% block content %}

<div class="modal-dialog">
        <div class="modal-content">
            <form class="">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <div><br>
                      <p>
                         メールアドレスを変更しました。<br>
                      </p>
                  </div>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-5">

                　          </div>
                    </div>
                  </div>
              </div>

           </form>
        </div>
      </div><br><br>
{% endblock %}

templates/register/email_change_form.html
{% extends "base.html" %}
{% block content %}


<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/register/login.html
{% extends "base.html" %}


<!------ Include the above in your HEAD tag ---------->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>お問い合わせ</title>
    <!-- CSS START -->
     <style type="text/css">
      .center {
      text-align: center;
      }
     </style>
    <!-- CSS END -->
</head>
{% block content %}

<body>

      <div class="modal-dialog">
        <div class="modal-content">
            <form class="log-in-form" action="{% url 'register:login' %}" method="POST">

              <div class="modal-header">
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >ログイン画面　</h3>
                  </div>
              </div>


              <div class="modal-body col-12">
                  <div>
                     {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                  </div>
              </div>

              <div class="modal-footer">
              <div class="container-fluid">
                <div class="row">

                        <div class="center col-4">
            　          </div>
                        <div class="center col-3">
                             {% csrf_token %}
                            <button type="submit" class="button expanded" >ログイン</button>
                            <input type="hidden" name="next" value="{{ next }}" />
            　          </div>
                </div>
                <div class="row">
                        <div class="center ">
            　          </div>
                        <div class="center col-12">
                            <a href="{% url 'register:password_reset' %}" class="btn btn-success btn-lg btn-block" >パスワードを忘れた方</a>
                        </div>
                </div>
              </div>
              </div>
           </form>
        </div>
          </div>
        </div>
      </div>
    </div>
   </div>
  </div><br><br>
</body>
</html>

{% endblock %}

templates/register/password_change.html
{% extends "base.html" %}
{% block content %}

     <div class="modal-dialog">
        <div class="modal-content">
            <form class="">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-lg">送信</button>
                  </form>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-5">
                　          </div>
                    </div>
                  </div>
              </div>

           </form>
        </div>
      </div><br><br>
{% endblock %}

templates/register/password_change_done.html
{% extends "base.html" %}
{% block content %}

<div class="modal-dialog">
        <div class="modal-content">
            <form class="">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <div>
                    <p>
                        パスワードを変更しました。<br>
                    </p>
                   </div>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-5">
                                <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
                　          </div>
                    </div>
                  </div>
              </div>

           </form>
        </form>
      </div><br><br>
{% endblock %}

templates/register/password_reset_complete.html
{% extends "base.html" %}
{% block content %}

<div class="modal-dialog">
        <div class="modal-content">
            <form class="">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <div><br>
                    <p>
                        パスワード再設定を完了しました。<br>
                    </p>
                   </div><br>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-12">
                                <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
                　          </div>
                    </div>
                  </div>
              </div>

           </form>
        </form>
      </div><br><br>
</div>
{% endblock %}

templates/register/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
<div class="modal-dialog">
        <div class="modal-content">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-lg">送信</button>
                   </form>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-5">
                　          </div>
                    </div>
                  </div>
              </div>

        </div>
      </div><br><br>

{% endblock %}

templates/register/password_reset_done.html
{% extends "base.html" %}

{% block content %}

      <div class="modal-dialog">
        <div class="modal-content">
            <form class="">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <div><br>
                      <p>
                            パスワード再設定用のメールを送信しました。<br>
                            メールに記載されているリンクから再設定を行ってください。
                      </p><br>
                  </div>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-5">
                　          </div>
                    </div>
                  </div>
              </div>

           </form>
        </div>
      </div><br><br>

{% endblock %}

templates/register/password_reset_form.html
{% extends "base.html" %}
{% block content %}



      <div class="modal-dialog">
        <div class="modal-content">


              <div class="modal-body">
                  <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-lg">送信</button>
                  </form>
              </div>

        </div>
      </div><br><br>

{% endblock %}

templates/register/user_create.html
{% extends "base.html" %}
{% block content %}
<body>

      <div class="modal-dialog">
        <div class="modal-content">

            <form method="POST" enctype="multipart/form-data">
              <div class="modal-header">

                  {% csrf_token %}
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >会員登録</h3>
                  </div>　
              </div>

              <div class="modal-body">
                  <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    <div class="modal-footer">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="center col-5">
                        　      </div>
                                <button type="submit" class="btn btn-primary btn-lg">送信</button>
                            </div>
                        </div>
                    </div>
                </form>
                </div>
              </div>
              </div><br><br>
{% endblock %}

templates/register/user_create_complete.html
{% extends "base.html" %}
{% block content %}

      <div class="modal-dialog">
        <div class="modal-content">
            <form class="">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <div><br>
                      <p>
                        本登録が完了しました。<br><br>
                        登録されたメールアドレスとパスワードでログインしてください。<br>

                      </p>
                  </div>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-12">
                                <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
                　          </div>
                    </div>
                  </div>
              </div>

           </form>
        </div>
      </div><br><br>
{% endblock %}

templates/register/user_create_done.html
{% extends "base.html" %}
{% block content %}

<div class="modal-dialog">
        <div class="modal-content">
            <form class="">

              <div class="modal-header">
                  <div class="center col-12"><br>
                    <h3 id="myModalLabel" >確認　</h3>
                  </div>
              </div>

              <div class="modal-body">
                  <div><br>
                      <p>
                        会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br><br>
                        確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
                      </p>
                  </div>
              </div>

              <div class="modal-footer">
                  <div class="container-fluid">
                    <div class="row">
                            <div class="center col-5">

                　          </div>
                    </div>
                  </div>
              </div>

           </form>
        </div>
      </div><br><br>
{% endblock %}

templates/register/user_detail.html
{% extends "base.html" %}
{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>ユーザー名</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>姓</th>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <th>名</th>
            <td>{{ user.first_name }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/register/user_form.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
</form>
{% endblock %}