config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('register.urls')),
    path('', include('my_page.urls')),
    path('', include('diagnotis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = 'home'




urlpatterns = [
    ##COMPLETE
    path('', views.Top.as_view(), name='top'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('question/', views.Question.as_view(), name='question'),
    path('instructions/', views.Instructions.as_view(), name='instructions'),
    path('order_job/', views.Order_Job.as_view(), name='order_job'),

    path('research_result/', views.ResearchResult.as_view(), name='research_result'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_detail'),
    path('like/<int:order_id>', views.like, name='like'),

    path('role_choice/', views.RoleChoice.as_view(), name='role_choice'),
    path('add_role/',views.addRole, name='add_role'),
    path('add_profile/',views.addProfile,name="add_profile"),
    path('change_profile',views.change_profile,name="change_profile")

]

my_page/urls.py
from django.urls import path
from . import views


app_name = 'my_page'


urlpatterns = [
    path('my_menu/', views.menu, name='my_menu'),

    path('order_submit/<int:order_id>', views.submit, name='submit'),


    path('profile/', views.Profile.as_view(), name='profile'),

    path('register_info/', views.Register_Info.as_view(), name='register_info'),
    path('orderer_info/', views.Orderer_Info.as_view(), name='orderer_info'),
    path('contractor_info/', views.Contractor_Info.as_view(), name='contractor_info'),

    path('message/', views.message, name='message'),
    path('message/<int:customer_id>/', views.message, name='message_detail'),

    path('order_decide/<int:order_id>/<int:customer_id>/', views.order_decide, name='order_decide'),

    path('pay/<int:order_id>', views.pay, name='pay'),
    path('pay_credit/<int:order_id>',views.pay_credit,name='pay_credit'),

    path('cancel/<int:order_id>',views.cancel,name='cancel'),
    path('order_fin/<int:order_id>',views.order_fin,name='order_fin'),
    path('complete/<int:order_id>', views.complete, name="complete"),


    path('favorite_list/', views.Favorite_List.as_view(), name='favorite_list'),
    path('request_job/', views.Request_Job.as_view(), name='request_job'),
    path('consent_list/', views.Consent_list.as_view(), name='consent_list'),
    path('trade_list/', views.Trade_list.as_view(), name='trade_list'),
    path('complate_list/', views.Complate_list.as_view(), name='complate_list'),



    path('comfirm/', views.Comfirm.as_view(), name='comfirm'),
    path('change/', views.Change.as_view(), name='change'),
    path('approval/', views.Approval.as_view(), name='approval'),
    path('cancel/', views.Cancel.as_view(), name='cancel'),
    path('complate/', views.Complate.as_view(), name='complate'),

]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),

    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

templates/base.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->



<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>トップページ</title>

        <!-- Fonts -->


        <style type="text/css">


        /******************* content *****************/
        body{
              font-family: 'Nunito', sans-serif;
            }
            .jumbotron-odi-hero{
            padding: 0rem 0rem;
             position: relative;
             max-width: 100%;

            }
            .jumbotron-odi-dark{
             max-width: 100%;
             padding: 0px;

            }

            .jumbotron-overlay {
             height:100%;
             padding: 100px 0;
             color:#fff;

            }
            .jumbotron-padding{
             padding-top: 6rem;

            }

            .btn-circle {
               border-radius: 30px;
            }

            .latest-news {
             border-bottom: .25rem solid transparent;
             border-bottom-color: #007bff;
            }

            .how-section1{
                margin-top:-20%;
                padding: 13%;
            }
            .how-section1 h4{
                color: #fffff;
                font-weight: bold;
                font-size: 30px;
            }
            .how-section1 .subheading{
                color: #3931af;
                font-size: 20px;
            }
            .how-section1 .row
            {
                margin-top: 20%;
            }
            .how-img
            {
                text-align: center;
            }
            .how-img img{
                width: 100%;
            }
        /******************* content *****************/

        /* Footer */
        @import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
        section {
            padding: 60px 0;
        }

        section .section-title {
            text-align: center;
            color: #007b5e;
            margin-bottom: 50px;
            text-transform: uppercase;
        }
        #footer {
            background: #6B6B75 !important;
        }
        #footer h5{
            padding-left: 10px;
            border-left: 3px solid #eeeeee;
            padding-bottom: 6px;
            margin-bottom: 20px;
            color:#ffffff;
        }
        #footer a {
            color: #ffffff;
            text-decoration: none !important;
            background-color: transparent;
            -webkit-text-decoration-skip: objects;
        }
        #footer ul.social li{
            padding: 3px 0;
        }
        #footer ul.social li a i {
            margin-right: 5px;
            font-size:25px;
            -webkit-transition: .5s all ease;
            -moz-transition: .5s all ease;
            transition: .5s all ease;
        }
        #footer ul.social li:hover a i {
            font-size:30px;
            margin-top:-10px;
        }
        #footer ul.social li a,
        #footer ul.quick-links li a{
            color:#ffffff;
        }
        #footer ul.social li a:hover{
            color:#3b5998;
        }
        #footer ul.quick-links li{
            padding: 3px 0;
            -webkit-transition: .5s all ease;
            -moz-transition: .5s all ease;
            transition: .5s all ease;
        }
        #footer ul.quick-links li:hover{
            padding: 3px 0;
            margin-left:5px;
            font-weight:700;
        }
        #footer ul.quick-links li a i{
            margin-right: 5px;
        }
        #footer ul.quick-links li:hover a i {
            font-weight: 700;
        }

        @media (max-width:767px){
            #footer h5 {
            padding-left: 0;
            border-left: transparent;
            padding-bottom: 0px;
            margin-bottom: 10px;
        }
        }
        /* Footer */

        .img {
            background-image: url(/media/img/top.png);
            background-size: cover;
            background-repeat: no-repeat;
            width:100%;
            height:550px;
        }
        .img-rounded{
            border-radius: 20px;
        }
        .center {
          text-align: center;
        }
        .section1{
                color: #fffff;
                font-weight: bold;
                font-size: 50px;
        }

        </style>
    </head>

    <body>
    <!-- navbar starts -->
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark nav-masthead">
            <div class="container">

              <a class="navbar-brand" href="#"> <h3 class="masthead-brand mb-0"><i class="fas fa-fire-alt"></i></h3></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <a class="nav-link p-2 font-weight-bold text-white" href="/">Weeet</a>
                  </li>
                </ul>


                {% if user.is_authenticated %}
                  <!--ログイン後の表示-->
                   <a class="nav-link text-white p-2 font-weight-bold" href="{% url 'my_page:my_menu' %}">マイメニュー</a>
                   <a class="nav-link text-white p-2 font-weight-bold" href="{% url 'register:logout' %}">ログアウト</a>
                  {% else %}
                   <a class="nav-link text-white p-2 font-weight-bold" href="/user_create">会員登録</a>
                   <a class="nav-link text-white p-2 font-weight-bold" href="/login">ログイン</a>
                  {% endif %}


              </div>
            </div>
            </nav>
    <!-- nav bar ends -->
<br>
<br>
<br>
<br>

    {% block content %}{% endblock %}

<!-- Footer -->
	<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left">

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <a class="nav-link p-2 font-weight-bold text-white" href="{% url 'home:top' %}">
                        <font color="#ffffff"><h1>Weeet</h1></font>
				        <br>
				        <br>
                    </a>
				</div>

				<div class="col-xs-12 col-sm-4 col-md-3">
					<h5>メニュー</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="/user_create/"><i class="fa fa-angle-double-right"></i>会員登録</a></li>
						<li><a href="/login"><i class="fa fa-angle-double-right"></i>ログイン</a></li>
						<li><a href="{% url 'home:research_result' %}"><i class="fa fa-angle-double-right"></i>仕事を探す</a></li>
						<li><a href="{% url 'home:order_job' %}"><i class="fa fa-angle-double-right"></i>仕事の依頼</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-3">
					<h5>サポート</h5>
					<ul class="list-unstyled quick-links">
                        <li><a href="{% url 'home:contact' %}"><i class="fa fa-angle-double-right"></i>お問合せ</a></li>
						<li><a href="{% url 'home:question' %}"><i class="fa fa-angle-double-right"></i>よくある質問</a></li>
                    </ul>
				</div>


			</div>

            <!-- 3月実装予定
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="https://facebook.com/ViccoFamily" target="_blank"><i class="fa fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href="https://twitter.com/Vicco" target="_blank"><i class="fa fa-twitter"></i></a></li>
						<li class="list-inline-item"><a href="https://instagram.com/Vicco" target="_blank"><i class="fa fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="https://www.youtube.com/user/ViccoFamily" target="_blank"><i class="fa fa-youtube"></i></a></li>
						<li class="list-inline-item"><a href="mailto:info@viccoshop.com.tr" target="_blank"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
			</div>-->

			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
				    <br>
                    <br>
					<p class="h6">
                        <font color="#ffffff">Copyright (c) 2020 Weeet　All Rights Reserved.</font>
                    </p>
				</div>
            </div>

		</div><font color="#000000">
	</font></section><font color="#000000">
<!-- ./Footer -->


    </body>
</html>

templates/coming_soon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <!-- CSS START -->
    <style type="text/css">
    .vh-100{
      height: 100vh;
      min-height:100vh;
    }
    </style>
    <!-- CSS END -->
</head>
<body>
    <div class="container">
      <div class="row vh-100 align-items-center">
        <div class="col text-center">
          <div class="content">
            <h1>Coming soon.</h1>
            <h6>This site will be released in the first week of March.</h6>
          </div>
        </div>
      </div>
    </div>
</body>
</html>