config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('register.urls')),
    path('', include('my_page.urls')),
    path('', include('diagnotis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = 'home'




urlpatterns = [
    ##COMPLETE
    path('', views.Top.as_view(), name='top'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('question/', views.Question.as_view(), name='question'),
    path('instructions/', views.Instructions.as_view(), name='instructions'),
    path('order_job/', views.Order_Job.as_view(), name='order_job'),

    path('research_result/', views.ResearchResult.as_view(), name='research_result'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_detail'),
    path('like/<int:order_id>', views.like, name='like'),

    path('role_choice/', views.RoleChoice.as_view(), name='role_choice'),
    path('add_role/',views.addRole, name='add_role'),
    path('add_profile/',views.addProfile,name="add_profile"),
    path('change_profile',views.change_profile,name="change_profile")

]

my_page/urls.py
from django.urls import path
from . import views


app_name = 'my_page'


urlpatterns = [
    path('my_menu/', views.menu, name='my_menu'),

    path('order_submit/<int:order_id>', views.submit, name='submit'),


    path('profile/', views.Profile.as_view(), name='profile'),

    path('register_info/', views.Register_Info.as_view(), name='register_info'),
    path('orderer_info/', views.Orderer_Info.as_view(), name='orderer_info'),
    path('contractor_info/', views.Contractor_Info.as_view(), name='contractor_info'),

    path('message/', views.message, name='message'),
    path('message/<int:customer_id>/', views.message, name='message_detail'),

    path('order_decide/<int:order_id>/<int:customer_id>/', views.order_decide, name='order_decide'),

    path('pay/<int:order_id>', views.pay, name='pay'),
    path('pay_credit/<int:order_id>',views.pay_credit,name='pay_credit'),

    path('cancel/<int:order_id>',views.cancel,name='cancel'),
    path('order_fin/<int:order_id>',views.order_fin,name='order_fin'),
    path('complete/<int:order_id>', views.complete, name="complete"),


    path('favorite_list/', views.Favorite_List.as_view(), name='favorite_list'),
    path('request_job/', views.Request_Job.as_view(), name='request_job'),
    path('consent_list/', views.Consent_list.as_view(), name='consent_list'),
    path('trade_list/', views.Trade_list.as_view(), name='trade_list'),
    path('complate_list/', views.Complate_list.as_view(), name='complate_list'),



    path('comfirm/', views.Comfirm.as_view(), name='comfirm'),
    path('change/', views.Change.as_view(), name='change'),
    path('approval/', views.Approval.as_view(), name='approval'),
    path('cancel/', views.Cancel.as_view(), name='cancel'),
    path('complate/', views.Complate.as_view(), name='complate'),

]

my_page/models.py
from django.db import models

# Create your models here.

my_page/forms.py
from register.models import User
from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('last_name', 'first_name')

my_page/views.py
from django.shortcuts import render,redirect
from django.views import generic
from register.models import User
from .forms import UserForm
from django.contrib.auth.decorators import login_required
from home.models import Like,Order,OrderMessage,MakerProfile,BuyerProfile
from home.models import MstStatus as MstStatusModel
from django.db.models import Q
import datetime
import requests

#マイページトップ
# ログインした人だけ見れるよ。

@login_required
def menu(request):
    if request.user.user_role is None:
        return redirect("/role_choice")

    elif request.user.user_role.id==1:
        profile = MakerProfile.objects.get(user=request.user)

        my_orders = Order.objects.filter(
            Q(maker_decided=request.user),
            Q(status=MstStatusModel.objects.get(id=2))|
            Q(status=MstStatusModel.objects.get(id=3)))

        my_fin_orders=Order.objects.filter(
            Q(maker_decided=request.user),
            Q(status=MstStatusModel.objects.get(id=6))|
            Q(status=MstStatusModel.objects.get(id=4))|
            Q(status=MstStatusModel.objects.get(id=5)))

        likes = Like.objects.filter(user=request.user, like_order__status__id=1)

        data={
            'likes':likes,
            'profile':profile,
            'my_orders':my_orders,
            'my_fin_orders':my_fin_orders,

        }
        return render(request,'my_page/my_menu.html',data)

    else:
        profile = BuyerProfile.objects.get(user=request.user)

        my_orders = Order.objects.filter(
            Q(buyer=request.user),
            Q(status=MstStatusModel.objects.get(id=1)))

        my_decided_orders = Order.objects.filter(
            Q(buyer=request.user),
            Q(status=MstStatusModel.objects.get(id=2))|
            Q(status=MstStatusModel.objects.get(id=3))
        )
        my_fin_orders=Order.objects.filter(
            Q(buyer=request.user),
            Q(status=MstStatusModel.objects.get(id=6))|
            Q(status=MstStatusModel.objects.get(id=4))|
            Q(status=MstStatusModel.objects.get(id=5)))

        data={
            'my_decided_orders':my_decided_orders,
            'profile':profile,
            'my_orders':my_orders,
            'my_fin_orders':my_fin_orders,

        }
        return render(request,'my_page/my_menu_for_buyer.html',data)

def submit(request,order_id):
    order=Order.objects.get(id=order_id)
    order.makers.add(request.user)
    return redirect('/my_menu')




def order_decide(request,order_id,customer_id):
    order=Order.objects.get(id=order_id)
    order.status=MstStatusModel.objects.get(id=2)
    user=User.objects.get(id=customer_id)
    order.maker_decided=user
    order.order_confirm=True
    order.order_confirm_at=datetime.datetime.now()
    order.save()
    return redirect('/my_menu')


class Profile(generic.CreateView):
    template_name = 'my_page/profile_.html'


class Register_Info(generic.TemplateView):
    template_name = 'my_page/register_info.html'

class Orderer_Info(generic.TemplateView):
    template_name = 'my_page/orderer_info.html'

class Contractor_Info(generic.TemplateView):
    template_name = 'my_page/contractor_info.html'


def message(request,customer_id):
    if request.method=="POST":
        user = User.objects.get(id=customer_id)
        if request.user.user_role.id==1:
            OrderMessage.objects.create(
                buyer=user,
                maker=request.user,
                talker=request.user,
                body=request.POST["body"],
                file=request.FILES,
            )
        else:
            OrderMessage.objects.create(
                buyer=request.user,
                maker=user,
                talker=request.user,
                body=request.POST["body"],
                file=request.FILES,
            )
    talk_lists = {}
    user = User.objects.get(id=customer_id)
    if request.user.user_role.id==1:
        messages=OrderMessage.objects.filter(maker=request.user,buyer=user).order_by('updated_at')
        message_profile=BuyerProfile.objects.get(user=user)
        msgs = OrderMessage.objects.filter(maker=request.user).order_by('-updated_at')
        for message in msgs:
            profile=BuyerProfile.objects.get(user=message.buyer)
            talk_lists[message.buyer]=[profile,message.updated_at]
    else:
        messages=OrderMessage.objects.filter(buyer=request.user,maker=user).order_by('updated_at')
        message_profile = MakerProfile.objects.get(user=user)
        msgs = OrderMessage.objects.filter(buyer=request.user).order_by('-updated_at')
        for message in msgs:
            profile = MakerProfile.objects.get(user=message.maker)
            talk_lists[message.maker]=[profile,message.updated_at]
    data={
        "messages":messages,
        "talk_lists":talk_lists,
        'message_profile':message_profile,
    }
    return render(request,'my_page/message.html',data)


def complete(request,order_id):
    order=Order.objects.get(id=order_id)
    status=MstStatusModel.objects.get(id=6)
    order.status=status
    order.save()
    return redirect('/my_menu')



def pay(request, order_id):
    order=Order.objects.get(id=order_id)
    if order.order_pay:
        return redirect('/my_menu')
    data={
        'order':order
    }
    return render(request,'my_page/pay.html',data)


def pay_credit(request,order_id):
    if request.method=="POST":

        request_url = "https://api.pay.jp/v1/charges"
        params = {
            "amount": int(request.POST["cost"]),  # テスト用に金額を1000円で設定
            "currency": "jpy",
            "card": request.POST["payjp-token"]  # カードのトークン
        }
        requests.post(request_url, params, auth=('sk_test_b8ed4e1dfbe222ae1b8b8828', ""))
        order=Order.objects.get(id=order_id)
        status=MstStatusModel.objects.get(id=3)
        order.status=status
        order.order_pay=True
        order.order_pay_at=datetime.datetime.now()
        order.save()

    return redirect('/my_menu')


def cancel(request,order_id):
    order=Order.objects.get(id=order_id)
    order.status=MstStatusModel.objects.get(id=5)
    order.save()
    return redirect('/my_menu')

def order_fin(request,order_id):
    order=Order.objects.get(id=order_id)
    order.status=MstStatusModel.objects.get(id=4)
    order.order_finish=True
    order.order_finish_at=datetime.datetime.now()
    order.save()
    return redirect('/my_menu')

#マイページ　表の中
class Favorite_List(generic.TemplateView):
    template_name = 'my_page/favorite_list.html'

class Trade_list(generic.TemplateView):
    template_name = 'my_page/trade_list.html'

class Request_Job(generic.TemplateView):
    template_name = 'my_page/request_job.html'

class Consent_list(generic.TemplateView):
    template_name = 'my_page/consent_list.html'

class Complate_list(generic.TemplateView):
    template_name = 'my_page/complate_list.html'

#マイページ　表の中の機能
class Comfirm(generic.TemplateView):
    template_name = 'my_page/comfirm.html'

class Change(generic.TemplateView):
    template_name = 'my_page/change.html'

class Approval(generic.TemplateView):
    template_name = 'my_page/approval.html'

class Cancel(generic.TemplateView):
    template_name = 'my_page/cancel.html'

class Complate(generic.TemplateView):
    template_name = 'my_page/complate.html'

templates/my_page/my_menu.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<head>
  <title>マイメニュー</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style type="text/css">
      .center {
      text-align: center;
      }
  </style>
</head>


<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>{{user.get_full_name}}</h1></div>
    </div>

    <div class="row">
  		<div class="col-sm-3"><!--left col-->

          <div class="text-center">
              {% if profile.picture %}
            <img src="{{profile.picture.url}}" class="avatar img-circle img-thumbnail" alt="Image">
              {% else %}
              <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="Image">

              {% endif %}

              <a href="{% url 'my_page:profile' %}"><h6>プロフィール画像の編集</h6></a><br>

          </div></hr><br>


          <div class="panel panel-default">
            <div class="panel-heading center">ユーザ情報</div>
              {% if user.user_role.id == 1 %}
            <div class="panel-body center"><a href="{% url 'home:change_profile' %}">登録情報変更</a></div>
              {% else %}
            <div class="panel-body center"><a href="{% url 'home:change_profile' %}">登録情報変更</a></div>
              {% endif %}
          </div>
          <!--
          <ul class="list-group">
            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Shares</strong></span> 125</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> 13</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Posts</strong></span> 37</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Followers</strong></span> 78</li>
          </ul>-->



          <div class="panel panel-default">
            <div class="panel-heading center">仕事管理</div>
              {% if user.user_role.id == 1 %}
              <div class="panel-body center"><a href="{% url 'home:research_result' %}">仕事を探す</a></div>
              {% else %}
            <div class="panel-body center"><a href="{% url 'home:order_job' %}">仕事の依頼</a></div>
              {% endif %}
          </div>



        </div><!--/col-3-->
<div class="col-sm-9">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home">お気に入り</a>　　</li>
                <li><a data-toggle="tab" href="#pay">承諾依頼一覧</a>　　</li>
                <li><a data-toggle="tab" href="#fin">完了・キャンセル一覧</a>　　</li>
              </ul>


            <div class="tab-content">
                 <div class="tab-pane active" id="home">
                     <hr>
                    <div class="container">
                        <div class="row">

                            <div class="col-md-11 ">
                                  <div class="panel-body">
                                    <table class="table table-hover table-bordered table-list">
                                      <thead>
                                        <tr>
                                            <th class="center active">タイトル</th>
                                            <th class="center active">依頼日</th>
                                            <th class="center active">詳細</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                      {% for like in likes%}
                                              <tr>
                                                <td class="col-md-2 center">{{like.like_order.title}}</td>
                                                <td class="col-md-4 center">{{like.like_order.order_post_at|date:"SHORT_DATE_FORMAT"}}</td>
                                                <td class="col-md-2 center">

                                                  <a href="{% url 'my_page:message_detail' like.like_order.buyer.id %}"class="btn btn-default center">メッセージ</a>
                                                  <a href="{% url 'my_page:submit' like.like_order.id %}" class="btn btn-warning center" >申し込み</em></a>
                                                </td>
                                              </tr>
                                      {% endfor %}
                                      </tbody>
                                    </table>

                                  </div>

                            </div>
                        </div>
                    </div>
                 </div><!--/tab-pane-->

                <div class="tab-pane" id="pay">
                     <hr>
                    <div class="container">
                        <div class="row">

                            <div class="col-md-11 ">
                                  <div class="panel-body">
                                    <table class="table table-hover table-bordered table-list">
                                      <thead>
                                        <tr>
                                            <th class="center active">タイトル</th>
                                            <th class="center active">依頼日</th>
                                            <th class="center active">詳細</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                      {% for order in my_orders%}
                                              <tr>
                                                <td class="col-md-2 center">{{order.title}}</td>
                                                <td class="col-md-4 center">{{order.order_post_at|date:"SHORT_DATE_FORMAT"}}</td>
                                                <td class="col-md-2 center">

                                                  <a href="{% url 'my_page:message_detail' order.buyer.id %}"class="btn btn-default center">メッセージ</a>
                                                  {% if order.status.id ==  2%}
                                                    <p class="btn btn-success center" >支払待ち</p>
                                                    {% else%}
                                                    <a href="{% url 'my_page:complete' order.id %}" class="btn btn-warning center" >作成終了</em></a>
                                                    {% endif %}
                                                </td>
                                              </tr>
                                      {% endfor %}
                                      </tbody>
                                    </table>

                                  </div>

                            </div>
                        </div>
                    </div>
                 </div><!--/tab-pane-->

                <div class="tab-pane" id="fin">
                     <hr>
                    <div class="container">
                        <div class="row">

                            <div class="col-md-11 ">
                                  <div class="panel-body">
                                    <table class="table table-hover table-bordered table-list">
                                      <thead>
                                        <tr>
                                            <th class="center active">タイトル</th>
                                            <th class="center active">依頼日</th>
                                            <th class="center active">詳細</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                      {% for order in my_fin_orders%}
                                              <tr>
                                                <td class="col-md-2 center">{{order.title}}</td>
                                                <td class="col-md-4 center">{{order.order_post_at|date:"SHORT_DATE_FORMAT"}}</td>
                                                <td class="col-md-2 center">

                                                  <a href="{% url 'my_page:message_detail' order.buyer.id %}"class="btn btn-default center">メッセージ</a>

                                                    {% if order.status.id == 4 %}
                                                    <p class="btn btn-success center" >完了</p>
                                                    {% elif order.status.id == 5 %}
                                                    <p class="btn btn-secondary center" >キャンセル</p>
                                                    {% elif order.status.id == 6 %}
                                                    <p class="btn btn-info center" >検収中</p>
                                                    {% endif %}
                                                </td>
                                              </tr>
                                      {% endfor %}
                                      </tbody>
                                    </table>

                                  </div>

                            </div>
                        </div>
                    </div>
                 </div><!--/tab-pane-->

          　</div><!--/tab-content-->
        </div><!--/col-9-->
    </div><!--/row-->

templates/my_page/my_page.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<head>
  <title>マイメニュー</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style type="text/css">
      .center {
      text-align: center;
      }
  </style>
</head>


<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>User name</h1></div>
    </div>

    <div class="row">
  		<div class="col-sm-3"><!--left col-->

          <div class="text-center">
            <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
              <a href="{% url 'my_page:profile' %}"><h6>プロフィール画像の編集</h6></a><br>

          </div></hr><br>


          <div class="panel panel-default">
            <div class="panel-heading center">ユーザ情報</div>
            <div class="panel-body center"><a href="{% url 'my_page:register_info' %}">ユーザ情報の登録・変更</a></div>
            <div class="panel-body center"><a href="{% url 'my_page:orderer_info' %}">発注者情報の登録・変更</a></div>
            <div class="panel-body center"><a href="{% url 'my_page:contractor_info' %}">受注者情報の登録・変更</a></div>
          </div>
          <!--
          <ul class="list-group">
            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Shares</strong></span> 125</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> 13</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Posts</strong></span> 37</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Followers</strong></span> 78</li>
          </ul>-->

          <div class="panel panel-default">
            <div class="panel-heading center">チャット機能</div>
            <div class="panel-body center"><a href="{% url 'my_page:message' %}">ダイレクトメッセージ</a></div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading center">仕事管理</div>
            <div class="panel-body center"><a href="{% url 'home:order_job' %}">仕事の依頼</a></div>
            <div class="panel-body center"><a href="{% url 'home:research_form' %}">仕事を探す</a></div>
            <div class="panel-body center"><a href="{% url 'home:research_result' %}">検索結果</a></div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading center">臨時メニュー</div>
            <div class="panel-body center"><a href="{% url 'my_page:favorite_list' %}">お気に入り</a></div>
            <div class="panel-body center"><a href="{% url 'my_page:request_job' %}">依頼履歴</a></div>
            <div class="panel-body center"><a href="{% url 'my_page:consent_list' %}">承諾依頼</a></div>
            <div class="panel-body center"><a href="{% url 'my_page:trade_list' %}">取引一覧</a></div>
            <div class="panel-body center"><a href="{% url 'my_page:complate' %}">完了・キャンセル</a></div>
          </div>

        </div><!--/col-3-->


    	<div class="col-sm-9">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home">お気に入り</a></li>
                <li><a data-toggle="tab" href="#messages">お仕事依頼一覧</a></li>
                <li><a data-toggle="tab" href="#settings">承諾依頼一覧</a></li>
                <li><a data-toggle="tab" href="#settings">取引一覧</a></li>
                <li><a data-toggle="tab" href="#settings">完了・キャンセル一覧</a></li>
              </ul>


            <div class="tab-content">
                 <div class="tab-pane active" id="home">
                     <hr>
                  <form class="form" action="##" method="post" id="registrationForm">
                    <div class="container">
                        <div class="row">

                            <div class="col-md-11 ">
                                  <div class="panel-body">
                                    <table class="table table-hover table-bordered table-list">
                                      <thead>
                                        <tr>
                                            <th class="center active">依頼日</th>
                                            <th class="center active">タイトル</th>
                                            <th class="center active">詳細</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                              <tr>
                                                <td class="col-md-2 center">2020/xx/xx</td>
                                                <td class="col-md-4 center">「Web作成依頼」</td>
                                                <td class="col-md-2 center">
                                                  <a class="btn btn-default center">メッセージ</a>
                                                  <a class="btn btn-warning center">申し込み</em></a>
                                                </td>
                                              </tr>
                                      </tbody>

                                      <tbody>
                                              <tr>
                                                <td class="col-md-2 center">2020/xx/xx</td>
                                                <td class="col-md-4 center">「Web作成依頼」</td>
                                                <td class="col-md-2 center">
                                                  <a class="btn btn-default center">メッセージ</a>
                                                  <a class="btn btn-warning center">申し込み</em></a>
                                                </td>
                                              </tr>
                                      </tbody>
                                    </table>

                                  </div>

                            </div>
                        </div></div>
              	  </form>
                 </div><!--/tab-pane-->

                 <div class="tab-pane" id="messages">
                     <hr>
                      <form class="form" action="##" method="post" id="registrationForm">

                        <div class="container">
                        <div class="row">

                        </div></div></div>
                      </form>
                 </div><!--/tab-pane-->

                 <div class="tab-pane" id="settings">
                      <hr>
                      <form class="form" action="##" method="post" id="registrationForm">

                      </form>
                 </div><!--/tab-pane-->

          　</div><!--/tab-content-->
        </div><!--/col-9-->
    </div><!--/row-->

templates/my_page/pay.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
{% endblock %}
{% block js %}
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}

<h3>{{order.maker_decided.get_full_name}}様</h3>
<h3>{{order.cost}}円</h3>
<form action="{% url 'my_page:pay_credit' order.id %}" method="post">
{% csrf_token %}
    <input type="hidden" value={{order.buyer.email}} name="email">
    <input type="hidden" name="cost" value="{{order.cost}}">
<script class="payjp-button" src="https://checkout.pay.jp/" data-key="pk_test_ea7952fabe400bde907c284d"></script>
</form>

{% endblock %}